name = "MakieUtils"
uuid = "56ac5d9f-1d55-43ba-8dff-4a3b3598aed1"
authors = ["Benoît Richard <kolaru@hotmail.com>"]
version = "0.1.0"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
LaTeXStrings = "1.4.0"
Makie = "0.22.2"
